### ISSUE TITLE
Source of the data

### ISSUE THREAD

**Issue by Alejo-Huawei** [r-papso/carca-replication#6]
I like this repository since the unique version I had so far from the model was in TF1. Taking a look at the preprocessing, there are some files loaded that I can not find. For example the "sbert_{mode}.p" file. Searching only I can find some image embeddings but not any sentence-bert embodies for this dataset. Would it be possible to know the link to the files used for the model?

Thank you

**Comment by r-papso** [comment]
Hello @Alejo-Huawei,

I assume that your question is about the code in preprocessing.ipynb notebook. Please note that all jupyter notebooks in this repository are intended to be used within my own experiments. That is the reason you cannot find files with Sentence-BERT embeddings. I cannot provide these files publicly as I have not enough storage space on the cloud. However, you can obtain those embeddings from textual descriptions of the products, such as titles and descriptions. Otherwise, you can ignore the usage of Sentence-BERT embeddings and use your own features (either one-hot encoded categorical product attributes or image features, that I believe are publicly available).

Thank you for reaching me out, if there is something else I can help with, please let me know.

**Comment by Alejo-Huawei** [comment]
Hello @r-papso. Thank you so much for your fast answer. I thought those sentence embeddings could be public somewhere else. I will try to encode the "reviewText" key value in the original data with Sbert and try with them. I will create another issue if needed; in the meantime, this one can be closed.
